openapi: 3.0.0
info:
  title: Products Service API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Returns a list of products
      tags:
        - Products
      responses:
        '200':
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorWithDetailsResponse'
    post:
      summary: Creates a new product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        '201':
          description: Created product object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid product data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorWithDetailsResponse'
  /products/{productId}:
    get:
      summary: Returns a product by ID
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single product object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Product ID is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageResponse'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageResponse'
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - title
        - price
        - count
      properties:
        id:
          type: string
          example: '7567ec4b-b10c-48c5-9345-fc73c48a80a2'
        title:
          type: string
          example: 'Product One'
        description:
          type: string
          example: 'Short Description'
        price:
          type: integer
          example: 24
        count:
          type: integer
          example: 10
    CreateProductRequest:
      type: object
      required:
        - title
        - price
        - count
      properties:
        title:
          type: string
          example: 'Product One'
        description:
          type: string
          example: 'Short Description'
        price:
          type: integer
          example: 24
        count:
          type: integer
          example: 10
    ErrorMessageResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'Internal Server Error'
    ErrorWithDetailsResponse:
      type: object
      required:
        - message
        - error
      properties:
        message:
          type: string
          example: 'Internal Server Error'
        error:
          type: string
          example: 'Table names are not defined in environment variables'
